### ISSUE TITLE
求懂中文的朋友帮忙看下

### ISSUE THREAD

**Issue by Cyiming** [nelenkov/android-backup-extractor#108]
我英文不好看不太懂介绍 勉强弄的 看看我这个文件还有救么

我操作的步骤如下：
1、下载了最新的abe.jar文件 并放在了目标文件backup_data.ab相同路径下
2、安装了jdk-19 并设置了系统变量
3、在目标文件下运行cad 输入命令：java -jar abe.jar unpack backup_data.ab backup_data.tar
`4、报错如下：PS D:\backup> java -jar abe.jar unpack backup_data.ab backup_data.tar
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "39 TWRP.security.e4crypt=2  1DK     "
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:232)
        at org.nick.abe.Main.main(Main.java:40)
Caused by: java.lang.NumberFormatException: For input string: "39 TWRP.security.e4crypt=2  1DK     "
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:665)
        at java.base/java.lang.Integer.parseInt(Integer.java:781)
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:72)
        ... 1 more`

**Comment by ZhReimu** [comment]
参考 https://github.com/nelenkov/android-backup-extractor/issues/121#issuecomment-1732797560
这个文件有问题，是 twrp 备份的，不是安卓自带的备份
