### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by GARZTHONGK** [nelenkov/android-backup-extractor#111]
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: ""
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:232)
        at org.nick.abe.Main.main(Main.java:40)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:662)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:72)
        ... 1 more

![image](https://user-images.githubusercontent.com/39154461/218562028-38750c9a-c768-4a32-853a-5ce3843d27ae.png)

**Comment by GARZTHONGK** [comment]
figured it out it didnt backup the file to my pc so the file was empty
