### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException

### ISSUE THREAD

**Issue by zai1208** [nelenkov/android-backup-extractor#121]
I get the following error when running `java -jar abe.jar unpack backup.ab backup.tar`
`Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "\ðÏ1-/data/media/0/TWRP/BACKUPS/1115fba1e4191c03/2023-09-17--21-33-22_QQ3A200605001/data.ext4.winTWRPtwdatablockDÝíº/bootchart/00407550003720000372000000000072131554257540012253xustar  shellshell58 RHT.security.selinux=u:object_r:bootchart_data_file:s0"
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:232)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.lang.NumberFormatException: For input string: "\ðÏ1-/data/media/0/TWRP/BACKUPS/1115fba1e4191c03/2023-09-17--21-33-22_QQ3A200605001/data.ext4.winTWRPtwdatablockDÝíº/bootchart/00407550003720000372000000000072131554257540012253xustar  shellshell58 RHT.security.selinux=u:object_r:bootchart_data_file:s0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:72)
	... 1 more
`

**Comment by nelenkov** [comment]
This does not look like an Android backup file. How was this created? 

Looking at the error message, it might be a backup created with [TWRP recovery](https://twrp.me/), in that case you would need TWRP to restore, and look at their source code/dos if you want to know about the format.
