### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: " 3☺←c"

### ISSUE THREAD

**Issue by Yunoextract1** [nelenkov/android-backup-extractor#129]
So, I just tried with Java 22 and got this error while trying to extract the .ab.

Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: " 3☺←c"
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:232)
        at org.nick.abe.Main.main(Main.java:40)
Caused by: java.lang.NumberFormatException: For input string: " 3☺←c"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:588)
        at java.base/java.lang.Integer.parseInt(Integer.java:685)
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:72)
        ... 1 more

Did I do anything wrong?

**Comment by nelenkov** [comment]
How does the .ab file header look like?

**Comment by Yunoextract1** [comment]
Sorry. I'm still new to this so I don't know what is the header name of the file is. But here is the text of the .ab file.
![Picture](https://github.com/nelenkov/android-backup-extractor/assets/166295562/45ab04ac-1b13-4c96-85ba-7a0a915e7de3)

**Comment by Yunoextract1** [comment]
The .ab file is from a game I'm trying to rip and not really an android backup file. I assume it contain the png file.

**Comment by nelenkov** [comment]
This is some sort of unity serialization format, the extension happens to be same but it's not in Android backup format. This tool won't work, you'll have to figure if it's a standard thing or analyze the game to figure it out.
