### ISSUE TITLE
Illegal Key Size exception

### ISSUE THREAD

**Issue by DanDevine** [nelenkov/android-backup-extractor#28]
When trying to unpack, I'm getting the following exception:

java -jar build/libs/abe-all.jar unpack backup.ab backup.tar Foobar

Exception in thread "main" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:203)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:118)
	... 1 more

I built this with the "./gradlew" command on OSX, using both 'bcprov-jdk15on-152.jar' and 'bcprov-ext-jdk15on-152.jar' located in the 'lib' directory.

Any thoughts?

Thanks in advance.

**Comment by nelenkov** [comment]
You need to install the unlimited strength crypto policy for you JDK. 

http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

**Comment by lid** [comment]
I ran into this issue too. Could you add this to the docs, or perhaps provide more informative error?

**Comment by DanDevine** [comment]
Yeah,  its mentioned in the doc page, but it didn't sink in.

You also need to add the java crypto extensions with 'unlimited strength'
keys.  Simple download from Oracle, but separate from standard jdk.  Copy
two jars across to your jdk install and done.

Interesting is that I needed these same keys for the "Keystore Explorer"
tool too.

Good luck, should be cake.

**Comment by nelenkov** [comment]
@lid The unlimited unlimited strength policy requirement is mentioned in the linked blog post, but I guess not many people read that far. The message comes from the Oracle's JCE provider. I guess all of this could be avoided by simply adding BouncyCastle as the default provider, but for now I've just added the JCE requirements to the README.
