### ISSUE TITLE
Illegal Key Size on Version 3 Bundle (Nexus 6, OS 5.1)

### ISSUE THREAD

**Issue by 8u1a** [nelenkov/android-backup-extractor#31]
Tried this on a Nexus 6 running 5.1.  Received an exception regarding illegal key size.  Will try to make some time this week to look at the code and format further, but figured I'd report it up.

$ head b.ab
ANDROID BACKUP
3
1
AES-256
...

java -jar build/libs/abe-all.jar unpack ../b.ab ../b.tar 12345
Exception in thread "main" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:203)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1029)
	at javax.crypto.Cipher.implInit(Cipher.java:795)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:854)
	at javax.crypto.Cipher.init(Cipher.java:1374)
	at javax.crypto.Cipher.init(Cipher.java:1308)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:118)
	... 1 more

**Comment by 8u1a** [comment]
Never mind, should have read the section about JCE unlimited strength jurisdiction policy more carefully.

Works great on this build!
