### ISSUE TITLE
Given final block not properly padded

### ISSUE THREAD

**Issue by lakshmandev** [nelenkov/android-backup-extractor#33]
After extracting a backup.ab file(5.69GB) I get a backup.tar(6.01GB) but at the end I get the following error while running this in eclipse,

```
Calculated MK checksum (use UTF-8: true): AFBE26845CDE730DCC0B7D821656764FBF542DA4B819CA2B6368B8A0B4682C05
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: javax.crypto.BadPaddingException: Given final block not properly padded
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:203)
	at org.nick.abe.Main.main(Main.java:42)
Caused by: java.io.IOException: javax.crypto.BadPaddingException: Given final block not properly padded
	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:115)
	at javax.crypto.CipherInputStream.read(CipherInputStream.java:233)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:182)
	... 1 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:811)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:676)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:313)
	at javax.crypto.Cipher.doFinal(Cipher.java:2014)
	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:112)
	... 6 more
```

**Comment by nelenkov** [comment]
This usually means that either the password is not correct or the file is corrupt.

**Comment by lakshmandev** [comment]
Thanks but the password I'm providing is correct because I m using my global password and I've tried this for three times and I get the same error. Also the backup file I took from adb is properly taken and I got backup finished message. I took and backup twice and both the files ended up in sames size(5.69GB).

**Comment by lakshmandev** [comment]
If my backup.ab file is 5.69 GB how much size the backup.tar would be.? And I m able to open the tar file without any errors. I m just curious if this error message missed any file in my extracted tar file. How can I check if all the file present in the backup.ab are also present in backup.tar?
