### ISSUE TITLE
Parse error in header: Illegal semantic path

### ISSUE THREAD

**Issue by jomo** [nelenkov/android-backup-extractor#37]
I tried to extract calendar data from a full backup and restore it to my device.
It's a Google/LG Nexus 4 running CyanogenMod 12.1, Android 5.1.1.

It successfully decrypts it, but then apparently fails to extract it.

```shell
# ls -lah calendar_data.tar
-rw-r--r--  1 root  staff   1.5M Nov 30 20:27 calendar_data.tar
# tar -tf calendar_data.tar
apps/
apps/com.android.calendar/
apps/com.android.providers.calendar/
apps/org.sufficientlysecure.localcalendar/
apps/org.sufficientlysecure.localcalendar/_manifest
apps/org.sufficientlysecure.localcalendar/a/
apps/org.sufficientlysecure.localcalendar/a/org.sufficientlysecure.localcalendar-2.apk
apps/com.android.providers.calendar/_manifest
apps/com.android.providers.calendar/db/
apps/com.android.providers.calendar/sp/
apps/com.android.providers.calendar/sp/CalendarUpgradeReceiver.xml
apps/com.android.providers.calendar/db/calendar.db
apps/com.android.providers.calendar/db/calendar.db-journal
apps/com.android.calendar/_manifest
apps/com.android.calendar/r/
apps/com.android.calendar/sp/
apps/com.android.calendar/sp/_has_set_default_values.xml
apps/com.android.calendar/sp/calendar_alerts.xml
apps/com.android.calendar/sp/com.android.calendar_preferences.xml
apps/com.android.calendar/sp/com.android.calendar_preferences_no_backup.xml
apps/com.android.calendar/r/app_webview/
apps/com.android.calendar/r/app_webview/Web Data
apps/com.android.calendar/r/app_webview/Web Data-journal
# java -jar abe-all.jar pack calendar_data.{tar,ab} $password
1624064 bytes written to calendar_data.ab.
# head -4 calendar_data.ab
ANDROID BACKUP
1
1
AES-256
# adb restore calendar_data.ab
Now unlock your device and confirm the restore operation.
#
```

Logcat:
```logcat
D/AndroidRuntime(10630):          Calling main entry com.android.commands.bu.Backup
D/bu      (10630):                Beginning: restore
I/BackupManagerService( 2085):    Beginning full restore...
D/BackupManagerService( 2085):    Starting restore confirmation UI, token=954785733
W/ContextImpl( 2085):             Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:1266 com.android.server.backup.BackupManagerService.startConfirmationUi:8602 com.android.server.backup.BackupManagerService.fullRestore:8569 com.android.server.backup.Trampoline.fullRestore:268 android.app.backup.IBackupManager$Stub.onTransact:243
W/ContextImpl( 2085):             Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:1278 android.app.ContextImpl.startActivity:1267 com.android.server.backup.BackupManagerService.startConfirmationUi:8602 com.android.server.backup.BackupManagerService.fullRestore:8569 com.android.server.backup.Trampoline.fullRestore:268
I/ActivityManager( 2085):         START u0 {act=fullrest flg=0x10000000 cmp=com.android.backupconfirm/.BackupRestoreConfirmation (has extras)} from uid 1000 on display 0
I/am_home_stack_moved( 2085):     [0,0,1,1,startingNewTask]
I/am_create_task( 2085):          [0,222]
I/am_create_activity( 2085):      [0,181563705,222,com.android.backupconfirm/.BackupRestoreConfirmation,fullrest,NULL,NULL,276824064]
V/WindowManager( 2085):           addAppToken: AppWindowToken{345ad0df token=Token{52fc37e ActivityRecord{ad27139 u0 com.android.backupconfirm/.BackupRestoreConfirmation t222}}} to stack=1 task=222 at 0
I/am_pause_activity( 2085):       [0,1009361814,com.cyanogenmod.trebuchet/com.android.launcher3.Launcher]
I/am_on_paused_called( 2709):     [0,com.android.launcher3.Launcher]
I/am_home_stack_moved( 2085):     [0,0,1,1,startedActivity setFocusedActivity]
I/am_focused_activity( 2085):     [0,com.android.backupconfirm/.BackupRestoreConfirmation]
I/am_restart_activity( 2085):     [0,181563705,222,com.android.backupconfirm/.BackupRestoreConfirmation]
D/BackupManagerService( 2085):    Waiting for full restore completion...
V/WindowManager( 2085):           Adding window Window{3956c456 u0 Starting com.android.backupconfirm} at 3 of 9 (after Window{19daba9b u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher})
I/am_on_resume_called( 9262):     [0,com.android.backupconfirm.BackupRestoreConfirmation]
V/WindowManager( 2085):           Adding window Window{34fa59c4 u0 com.android.backupconfirm/com.android.backupconfirm.BackupRestoreConfirmation} at 3 of 10 (before Window{3956c456 u0 Starting com.android.backupconfirm})
I/am_activity_launch_time( 2085): [0,181563705,com.android.backupconfirm/.BackupRestoreConfirmation,138,138]
I/ActivityManager( 2085):         Displayed com.android.backupconfirm/.BackupRestoreConfirmation: +138ms
I/Timeline( 9262):                Timeline: Activity_idle id: android.os.BinderProxy@255d705f time:2077992
I/sf_frame_dur(  183):            [com.cyanogenmod.trebuchet/com.android.launcher3.Launcher,15,0,0,0,0,0,1]
I/Timeline( 2085):                Timeline: Activity_windows_visible id: ActivityRecord{ad27139 u0 com.android.backupconfirm/.BackupRestoreConfirmation t222} time:2078678
I/LatinIME( 2498):                Starting input. Cursor position = 0,0
I/notification_cancel( 2085):     [10007,2308,com.android.systemui,100,low_battery,-1,0,64,8,NULL]
I/LatinIME( 2498):                Starting input. Cursor position = 0,0
I/notification_cancel( 2085):     [10007,2308,com.android.systemui,100,low_battery,-1,0,64,8,NULL]
D/BackupManagerService( 2085):    acknowledgeFullBackupOrRestore : token=954785733 allow=true
D/BackupManagerService( 2085):    Sending conf message with verb 10
E/AudioTrack( 2085):              AudioTrack::set : Exit
I/BackupManagerService( 2085):    --- Performing full-dataset restore ---
I/BackupManagerService( 2085):    Initiating bind of OBB service on com.android.server.backup.BackupManagerService$FullBackupObbConnection@78b348
W/ContextImpl( 2085):             Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1798 com.android.server.backup.BackupManagerService$FullBackupObbConnection.establish:3041 com.android.server.backup.BackupManagerService$PerformAdbRestoreTask.run:5699 java.lang.Thread.run:818 <bottom of call stack>
I/BackupManagerService( 2085):    OBB service connection com.android.internal.backup.IObbBackupService$Stub$Proxy@2309bbf4 connected on com.android.server.backup.BackupManagerService$FullBackupObbConnection@78b348
I/notification_cancel( 2085):     [10007,2308,com.android.systemui,100,low_battery,-1,0,64,8,NULL]
I/dvm_lock_sample( 2085):         [system_server,0,ReferenceQueueDaemon,8,ReferenceQueue.java,135,-,90,1]
E/BackupManagerService( 2085):    Parse error in header: Illegal semantic path in
I/hexdump ( 2085):                0000   61 70 70 73 2f 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0010   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0020   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0030   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0060   00 00 00 00 30 30 30 37 35 35 20 00 30 30 30 30
I/hexdump ( 2085):                0070   30 30 20 00 30 30 30 30 30 30 20 00 30 30 30 30
I/hexdump ( 2085):                0080   30 30 30 30 30 30 30 20 31 32 36 32 37 30 32 37
I/hexdump ( 2085):                0090   31 37 30 20 30 31 32 31 32 34 00 20 35 00 00 00
I/hexdump ( 2085):                00a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                00d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                00e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                00f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0100   00 75 73 74 61 72 00 30 30 72 6f 6f 74 00 00 00
I/hexdump ( 2085):                0110   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0120   00 00 00 00 00 00 00 00 00 77 68 65 65 6c 00 00
I/hexdump ( 2085):                0130   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0140   00 00 00 00 00 00 00 00 00 30 30 30 30 30 30 20
I/hexdump ( 2085):                0150   00 30 30 30 30 30 30 20 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0160   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0170   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0180   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                0190   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                01a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                01b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                01c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                01d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                01e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
I/hexdump ( 2085):                01f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
W/BackupManagerService( 2085):    io exception on restore socket read
W/BackupManagerService( 2085):    java.io.IOException: Illegal semantic path in
W/BackupManagerService( 2085):    at com.android.server.backup.BackupManagerService$PerformAdbRestoreTask.readTarHeaders(BackupManagerService.java:6777)
W/BackupManagerService( 2085):    at com.android.server.backup.BackupManagerService$PerformAdbRestoreTask.restoreOneFile(BackupManagerService.java:5917)
W/BackupManagerService( 2085):    at com.android.server.backup.BackupManagerService$PerformAdbRestoreTask.run(BackupManagerService.java:5766)
W/BackupManagerService( 2085):    at java.lang.Thread.run(Thread.java:818)
I/BackupManagerService( 2085):    Full restore processing complete.
D/bu      (10630):                Finished.
D/AndroidRuntime(10630):          Shutting down VM
D/BackupManagerService( 2085):    Full restore pass complete.
I/am_finish_activity( 2085):      [0,181563705,222,com.android.backupconfirm/.BackupRestoreConfirmation,app-request]
I/am_home_stack_moved( 2085):     [0,1,0,0,finishActivity adjustFocus]
I/wm_task_moved( 2085):           [208,1,1]
I/am_home_stack_moved( 2085):     [0,1,0,0,finishActivity adjustTopFocus setFocusedActivity]
I/am_focused_activity( 2085):     [0,com.cyanogenmod.trebuchet/com.android.launcher3.Launcher]
W/art     ( 2085):                Long monitor contention event with owner method=android.graphics.Bitmap com.android.server.wm.WindowManagerService.screenshotApplications(android.os.IBinder, int, int, int, boolean) from WindowManagerService.java:6272 waiters=0 for 1.466s
I/dvm_lock_sample( 2085):         [system_server,1,android.display,1466,WindowAnimator.java,130,WindowManagerService.java,6272,100]
I/am_pause_activity( 2085):       [0,181563705,com.android.backupconfirm/.BackupRestoreConfirmation]
I/am_on_paused_called( 9262):     [0,com.android.backupconfirm.BackupRestoreConfirmation]
I/am_resume_activity( 2085):      [0,1009361814,208,com.cyanogenmod.trebuchet/com.android.launcher3.Launcher]
I/am_on_resume_called( 2709):     [0,com.android.launcher3.Launcher]
I/dvm_lock_sample( 2085):         [system_server,1,Binder_1,15,WindowManagerService.java,3082,WindowAnimator.java,130,3]
I/dvm_lock_sample( 2085):         [system_server,1,Binder_2,24,WindowManagerService.java,7514,-,3082,4]
I/Timeline( 2709):                Timeline: Activity_idle id: android.os.BinderProxy@b1a8a3f time:2099687
W/IInputConnectionWrapper( 9262): showStatusIcon on inactive InputConnection
I/am_destroy_activity( 2085):     [0,181563705,222,com.android.backupconfirm/.BackupRestoreConfirmation,finish-imm]
I/Timeline( 2085):                Timeline: Activity_windows_visible id: ActivityRecord{3c29a396 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t208} time:2099901
I/sf_frame_dur(  183):            [InputMethod,0,2,2,10,4,0,1]
I/wm_task_removed( 2085):         [222,removeAppToken: last token]
I/wm_task_removed( 2085):         [222,removeTask]
I/sf_frame_dur(  183):            [com.android.backupconfirm/com.android.backupconfirm.BackupRestoreConfirmation,113,2,3,11,14,10,0]
```

The hexdump from above represents:
```
apps/000755 000000 000000 00000000000 12627027170 012124 5ustar00rootwheel000000 000000
```
Those are the first 512 bytes of the `calendar_data.tar` file. `root…wheel` that's the user/group owning the files in the tar archive (on my machine). I also tried using a non-root user first, but that didn't work either.

Am I missing something? Do I need to specially craft the tar archive?

**Comment by nelenkov** [comment]
The error is happening on your device, so it's not a problem with the extractor. Not sure what your goal is but, repacking after modifying the tar file is somewhat tricky. You can find detailed guides on XDA, etc, e.g. this: http://forum.xda-developers.com/showthread.php?t=2011811

**Comment by jomo** [comment]
Thanks. The guide mentions to use star because it removes trailing slashes from directory names. I'll try that later.

**Comment by jomo** [comment]
It worked, thanks! I'll make a PR for the readme with some details I figured out.

**Comment by fadster** [comment]
I got the same error and resolved it by removing the directory entries from the file list used to create the tar file.
