### ISSUE TITLE
Illegal key size exception

### ISSUE THREAD

**Issue by tubaman** [nelenkov/android-backup-extractor#40]
I get this when trying to decrypt a Android 6.0 backup from Nexus 5x

```
This backup is encrypted, please provide the password
Password: 
Exception in thread "main" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:203)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1024)
	at javax.crypto.Cipher.implInit(Cipher.java:790)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:849)
	at javax.crypto.Cipher.init(Cipher.java:1348)
	at javax.crypto.Cipher.init(Cipher.java:1282)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:118)
	... 1 more

```

**Comment by nelenkov** [comment]
You need to install the JCE unlimited strength jurisdiction policy, see the README
