### ISSUE TITLE
java.security.InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by jvilhuber** [nelenkov/android-backup-extractor#43]
I have a backup from Android 6.0.1 (nexus 5x), which is encrypted, and no matter what I use as the password, I get the error message in the title:
```
Exception in thread "main" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:219)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1029)
	at javax.crypto.Cipher.implInit(Cipher.java:795)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:854)
	at javax.crypto.Cipher.init(Cipher.java:1374)
	at javax.crypto.Cipher.init(Cipher.java:1308)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:134)
	... 1 more
```

Since pbkdf2 is being used, it SHOULD create the right key-length, so I'm (so far) stumped. Not sure what other information I can provide. I turned on DEBUG=true, and see:
```
Magic: ANDROID BACKUP
Version: 3
Compressed: 1
Algorithm: AES-256
This backup is encrypted, please provide the password
Password:
```
where I enter the password. Next thing I see is the above error.

**Comment by nelenkov** [comment]
You need to install the JCE unlimited policy, see README

**Comment by jvilhuber** [comment]
Thanks!
