### ISSUE TITLE
failed extraction: java.lang.RuntimeException: java.lang.NumberFormatException: For input string

### ISSUE THREAD

**Issue by jontis** [nelenkov/android-backup-extractor#59]
jonathan@sandra ~/tmp_backup_onyx $ java -debug -jar abe-all.jar unpack backup.ab backup.tar
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "/addon.d/004075500000000000000000000000001323115710500111445ustar  rootroot/addon.d/50-cm.sh01007550000000000000000000000062111270740000012421xustar  rootroot50 RHT.security.selinux=u:object_r:system_file:s0"
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:233)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.lang.NumberFormatException: For input string: "/addon.d/004075500000000000000000000000001323115710500111445ustar  rootroot/addon.d/50-cm.sh01007550000000000000000000000062111270740000012421xustar  rootroot50 RHT.security.selinux=u:object_r:system_file:s0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:71)
	... 1 more

**Comment by locpv-ibl** [comment]
Same error, any helps?

**Comment by nelenkov** [comment]
look at the header (text lines) of your backup archive and see what's there.
If there are space or a different number format/order, maybe your phone is using slightly different format from what the tools expects. Should be easy to adjust if the difference is small.

**Comment by locpv-ibl** [comment]
@nelenkov Thanks, that was a point. The "backup.ab" was failed created so I think the abe does not recognize the file. I tried to backup again and when it asked my mobile phone for encrypted password then now it works, otherwise it won't work for abe :)

**Comment by 71walceli** [comment]
Well, the error may be somewhat misleading, 

```sh
$ ll
total 2336
drwxrwxr-x  3 wceli wceli    4096 feb 17 15:43 ./
drwxr-x--- 53 wceli wceli   32768 feb 17 15:35 ../
-rw-rw-r--  1 wceli wceli       4 feb  6 17:56 1
drwxrwxr-x  3 wceli wceli    4096 feb  4 17:25 a1/
-rw-rw-r--  1 wceli wceli 2327223 nov  9 01:31 abe.jar
-rw-r-----  1 wceli wceli       0 feb 16 18:29 backup2.ab
-rw-r-----  1 wceli wceli     549 feb 17 15:43 backup.ab
-rw-rw-r--  1 wceli wceli    1024 feb 17 15:43 backup.tar
```

It turns out the `backup2.ab` is the first one I made, which was 0 bytes. 

That's a check to be made before trying to decrypt and extract the file, as this exception leads to no useful understanding

**Comment by 71walceli** [comment]
Please check PR #112 in order to add several other ones so as to prevent misleading errors messages or ones that aren't really helpful.

**Comment by nelenkov** [comment]
Thanks @71walceli. I've merged that PR, but since the travis build is no longer running, you need to build from master.

**Comment by dginovker** [comment]
Also getting this issue
```
java -jar abe-62310d4.jar unpack abe-62310d4.jar backup.tar        1 ↵ wacket@archlinux
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string:²"     /Z META-INF/PK"
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:239)
        at org.nick.abe.Main.main(Main.java:40)
Caused by: java.lang.NumberFormatException: For input string:²" /Z      META-INF/PK"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:569)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:79)
        ... 1 more
```

Here's what the file looked like for me at the start

```
head -c 100 backup.ab                                                  wacket@archlinux
ANDROID BACKUP
5
1
none
x���uX���/j+%H� R"5�▒iPZp��n▒��E@$$ED   �               H)��;~��w��=�w�>�y����=��5��^%   
```
