### ISSUE TITLE
failed extraction: exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by lanredroidsmith** [nelenkov/android-backup-extractor#61]
I'm getting this while trying to extract. PLEASE HELP

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
?l?=?±ô?y: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid Magic xÄè?
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:502)
        at org.nick.abe.Main.main(Main.java:128)
        ... 5 more
?l?=?±ô?y: java.lang.IllegalArgumentException: Invalid Magic xÄè?
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:332)
        ... 6 more

**Comment by lanredroidsmith** [comment]
@nelenkov can you PLEASE look into this? Thanks.

**Comment by nelenkov** [comment]
Looks like an invalid archive?

**Comment by lanredroidsmith** [comment]
@nelenkov Sorry, I don't understand what you mean by 'invalid archive'. Backup was done this way:

- Went to command interface using Power key + volume up
- Scrolled to backup
- Selected it and it notified me when it was done

Phone is Infinix hot 4 pro

Thanks for your swift response.

**Comment by nelenkov** [comment]
What you have is most probably a full partition dump, not an ADB backup.
ADB backups are created using the 'adb backup' command while Android is running. 

The format of your backup depends on the recovery of your phone. It could be compressed, or a just a raw ext4, etc. image.

**Comment by lanredroidsmith** [comment]
Oh! OK...

Now I have separate '.backup' files after the exception was thrown - the original '.ab' file no longer exists. What would you advise I do to recover my original files?

Thanks a lot for your support.
