### ISSUE TITLE
Unpack faild

### ISSUE THREAD

**Issue by supercatreal** [nelenkov/android-backup-extractor#78]
I use the command in the Powershell，but it faild.
command：java -jar unpack pack.bak pack.tar
Error info：
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
        at org.nick.abe.Main.main(Main.java:128)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
        ... 6 more
Who can tell me the way to slove it？
Thank you a lot！

**Comment by gsgrippal** [comment]
There's a forked version of android backup extractor, try it and tell us.
https://sourceforge.net/projects/adbextractor/files/abe.jar/download

**Comment by superbonaci** [comment]
@supercatreal close this issue since it's fixed.
