### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: invalid code lengths set

### ISSUE THREAD

**Issue by quickishfm** [nelenkov/android-backup-extractor#81]
I get this error:

```
0% 1% 2% Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: invalid code lengths set
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:233)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.util.zip.ZipException: invalid code lengths set
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:165)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:205)
	... 1 more
```
when trying to uncompress an ab to a tar. There is no encryption. Is there a way to fix this at present?

Thank you.

**Comment by superbonaci** [comment]
Would help to have a backup sample.
