### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: 

### ISSUE THREAD

**Issue by eliezercazares** [nelenkov/android-backup-extractor#85]
Hello, I am in desperate need of help. Willing to pay whatever is possible for me. I have 6 backup files with tons of pictures of my cats from 5 yrs ago that I want so much to recover.

But I am getting this error, I was not asked for a password to encrypt the file by the BladeMax System Recovery device mode.

I have no idea what is going on, I know it might be encrypted but I have no idea about encryption.

Thanks for your time and your help!
-eliezer

```
sh-3.2# java -jar target/abe.jar unpack ../../../blademax/userdata_20100101_195418_2.backup ../../../blademax/userdata.tar
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "HW þ>Â2-]»>ÖzHÓÑáMg±ú"záÍcÿÖ¤8ì"ºç·]£6±¬¾`%hK*	õôJ<¨8÷¹>ª³wd^¯*&-,Á.!ü½quØsö%51l§Æ­lÞEñi©Ò¸kÇHËã½w­L¿ÙÝ¬týZuhÞÆ_kïh¡Ç
       ;´_×ÕI9QG¦ë_qKÌÒMvÛ`ýrÜ¹$<Wô <p©N ©E,í6b`ÕY¿¶óS/ÅãµZzì¬ú2¼¸S:@GþÊõµÕ±´<[·Â|´>¢*¢H¯CÆÍÿ£µ! ÏëøH¡¤Â[­:l¨§öp#NÁ¸
ÏÂd'äX(À>#Î"Ì5½né,*RJÊQ¢ î.1¿zÓ«r\yv"
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:233)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.lang.NumberFormatException: For input string: "HW þ>Â2-]»>ÖzHÓÑáMg±ú"záÍcÿÖ¤8ì"ºç·]£6±¬¾`%hK*	õôJ<¨8÷¹>ª³wd^¯*&-,Á.!ü½quØsö%51l§Æ­lÞEñi©Ò¸kÇHËã½w­L¿ÙÝ¬týZuhÞÆ_kïh¡Ç
                                       ;´_×ÕI9QG¦ë_qKÌÒMvÛ`ýrÜ¹$<Wô <p©N ©E,í6b`ÕY¿¶óS/ÅãµZzì¬ú2¼¸S:@GþÊõµÕ±´<[·Â|´>¢*¢H¯CÆÍÿ£µ! ÏëøH¡¤Â[­:l¨§öp#NÁ¸
ÏÂd'äX(À>#Î"Ì5½né,*RJÊQ¢ î.1¿zÓ«r\yv"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:660)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:71)
	... 1 more

```

**Comment by eliezercazares** [comment]
First 25 lines of ZTE brand backup sample file:

?u6	#?Ѱ?$?x????`?X?(ˤ??Zb?([.?s?ͯM#q?1???Dj9I P?o??!?	???b??Ed/?T??HXދ???.E???n~?c?q?#mbR5k?q`Jk?DA?W??c??^(??SKd<uDa????A??}c?8?7????bX?ݢ??o????봭??gygO&???A???cC#+b?????O????hNz??P3?$H??h?Q???A6g8?G?rc????;??a??IA??x?琾=c^©:}?`\ΰ?݌????X??eaX??hK???????+???C???Z6??9?~???vlI?^]g>91??1K????4??
???ehK?Po?$aZnh)&?~+le?C?             y?D??6???m?Ѹ??Ir?D?C2jt???3?uk4#?/??N??Ư;y?Qf???^???y?)h??r?%;h8?ׁ- ?:???ӄ?:?V?2????o?՝??snx-?o^ގ7j?> c???gA;?xJz?M{??7\?~0                        4?"??a"*ʝ?	??XLG}??6ʗl$??'?f?G+?Pz???2??v?bP???&?\?e??ƹ+?<?S??? Z?}q?c?2f֖%?%?P's?1??k?%[|fewh??ï????:tm	_?tH#????C??q?Q-%???!UU??????tt??,<??V??K/?????n     [T??ù?X?`f1\???V8H?????@k?bޮP?P??m?<.??2G(
3????.?                 ??s?@c?^c???aq?
       ;??Y??|??┡??y???dz?IE?%piпv?tW?O?/P?9???^?,KV???????<Ҋ
??B\???!᏾zXp*?M?hUF8J??}*?H~?瑩M??
L?능?~)̼???Z??+*?DB?ҡ? x??u|s????  Gf????KȔ(???????'?V&p???F??????8[e?E8?qtBjly ?$9?N?%??hb:<?b:)??5??+i?O???C???.PXk?RC?`??q?~T??MK???]?5W??!??:L???ẃ?B??a??UtKx?k????/?ʣ*??`?8(ZO1?b??{???8?????W?<PfD??_??p????RNΗ????%?SJLs?/?????*ڔ`ؘ1?$?Yn?GC??W?ߖѬ?ɱ?P??S+??@??n????߄?`?
??uy@???5Lp?yo???      ????  ?!@30.?BDu?V>?
H*Dp^?S4??S?Ǳ?I?F?~??{???O7C??g??K=e?s
?r?H?܉I??????i???~??ƾ???u??83???????C?@U?gf?gR???	?&?K?!?X?a???#Dfl?VQO?jO??lf????.?
)Ɇ#?d???߇hv>vTO?`(c?c?`??&??R??G<??:??1?<`?]O??}?B!?{?7u[B?*Ǖ?Z9??iK??????23@片
^??%,?%??+?Obg?]??=?l<S?H???#??^8}??*Q(ў?9??i??MA?9H??Е?/8                     S?g??CE6y?1?\?1R?I???4IU??&0}?M?z	K???^/?_}?EƷ?b?   ?.?[?g#??0RL/D??%??PZ?C?(!4                                                  ??lʹ0+??F`K^\?̇&<ӳ?huh4??L?Z????W?????L(c?Gm`?i??;????LK?X&-???둑-U*??Ĭ?fl?
?n?߰?e:](@?V;.???%
                 6???>O?e?ż??)?~?k?K̑???S8=?*?a?????C,I???x?
                                                           ?^????x6??W0Am???e?1?ݪM?Zd;??Ȫ???V???ÊEl?????? ?d??]??M$?H? ????y??n?
                                                ?L??$??蘕??g?Q??v3??:?D?"܀???w&[sS/#????B?5մӷ?n??S??v?lz??%?6?YKA8?S=ܵϊ&hH?vc?xg?>i-K}?94%h?{>ዾ??b<??ʛ8~??]????`???_d???d?I0'?
?ݱ;={???D?????H?P(Ղ??(???
??\r$???͜#Z?Y?̰hM?5?V?D?y*?{?,????N??\KFs\???d'??f?S??ٱ???E0 إD???-?oظM?r??v?0?
????R??+???W?hni4?O?[?K8?cIHM?I????C??
?????$_C????'???        ѼR??????q?>zZ???\?E??S?#?䕻?c??I???J7 ?-?*҈Q???x?c.RuÏ??28h??	?p?`tUY??(+	/?Ί???@z??t?7w?>?yt?ؘ??Ծ_-?<m??3?J???GO&,?!??a?o??Mm??}????ⅎ??AN????m@?y@"=?_?\?ā???(Q܅??F?ݾ?aP??????!??jo???TQ?
                                                       ??N????N?Rk??M9??AQ??"?i)?~6冾R?.G?Q?????R??pī90???vtޛO?Ȫ%???	Ł?Q???? ??d&"?׏??X'j?Z?N
??
?1??r???"P)????:r??|???r??l?
                            Ol}?bh;?{w~F???y???X9{4?M???L_?C??$?1)?&T?:?j??y??Q?73\#?ǵ+????<??5M??eN4?2U???W:?fz?
                                 ??P݀+?(L?i!?CG$??;h??&AYJ????#?Ȯ)|t??T??U??	?4?<O?,ڶ#?_?5:B??A????粃4A,T?Vו??ES???ؕ?9At?o??N????(y?{???????1F?dzv??"uk?;+?`??"<y?'A????Āf??v???Hp Mq??v??l???]?$m??Wvқa?Y?^/]??.??G?-??yg1FZ
X?:'????Ǵ??5v]????i?덈͠?GQ<????ӂM?ӷ0??e?j??
????_??A??xf=?,K}>#??Zʖ??+????*??????חH쎖?????-dw8s?_w?2U?S?b? ?
                                                                ??l)????      M?}??`??ӕ??%s+9{	K?Q??2G?Xۙ??^?9?????+P"~>???ϊ@?Վ?G?/??a???R?^??T"?h.?????9?!~l??t?$?1x)j?ό?33 ?D?s3܏~l?o???̇[?N??? ?b?aY???5??8??ƛ?Zi?pO_?_"B?????x???@|?1??L{?	47?8f+?a?7?h??????a[*ǻ???mf?󙒋N??MZH??7zZ?[???f???e?[:??w|r?x0a???G?
          =7fT???r
??8|??'??z??Y/?-?7?vG?????mM?,<^?Nگp?>?)3?{?Ô?4q???n?6?5O??U-????*???\ȪyHZ?.sU??ޕ?Ͱ??Ovm??9DcF??
                ??????????WT7???4?=??@$???S??F???g?C?ߣ?,??YO?V?oߖ?6	?jq0??_?x42???w?/?#?{ފ8?d?.V5?Z?I?96!1IZ??^?W9?k?Ƭ=/.?M?3???p???_H???a?hMޚ?i????p3;???
??v???F??E}x??tH}kz?ƽ%?t?6?????h???C?^M!??WV??h??U???8)RUB??-Y5????^Ʊ?:K?
???/???3[p???pag`
                 6A?H/????!i??^?W?y|ތ@?"??(Kq;?ǣ?\2????P??!"%$?9?h?????B<?-??L?g?tI?s?:6?j?6?&':??<f?
?ض??9?.?F?G????f??R"ڡcm???Sډ?a?	I??)<??NHnI}Ô$???0]`x?|᥽r?Mڒɔ	????;?B?????T?CU)???!R?bS],??Z[F?1C?A
                    ɱ????? (r??k(?<?&??wK7?!n4?I?^
                                                  ;????i??4ۆ?-%T?Sz?@6_괼?겙;I???dS??G? ?+'?@-??Q??E??l??Ov?N??U\??#?<??24???"?4?*8???r??7o??n????<P??=>)???8????a(?k?I?{7V?2{??Z???%?yhAR?t$?:?E??|?Η??????~????{_?????Y?;???Bڅ_??tM?? ?0?
                                                                            ??????CWB^??Ԅޤ;
??????=?C^oC?%?N??=???:9?9o
                           *??ͣn?M8Z?m])?k?Kr?\????x.E????+#?b~???f???Hń?u???}?k?
                                                                               ?9??FS?
?Pu??ϯU??\gw?
ܪ??dwy~?;ڔ:Z|?????IjRbS?E?????\w?????v+E}??NǱ蝼ŏ???<???W??M?{4&?ZO???b??_?el?T??2%???B?L??S?D?
Z?WM(???%|
$~Wh?T'?͜?E????7???@jzݲ?s???̙z?
                          ?`*£
                              -m??ˑ???zÑ?^?+F?ꃓjq

**Comment by nelenkov** [comment]
This seems to be a complete different format, there is no text header, so no idea really how it works.
