### ISSUE TITLE
Xiaomi MIUI health

### ISSUE THREAD

**Issue by dan-zong-hao** [nelenkov/android-backup-extractor#94]
This is the backup file I imported from my Xiaomi MIUI phone，
![image](https://user-images.githubusercontent.com/75935737/156777668-2fd7d9cc-630f-49a6-977a-365a632960c1.png)
Then I deleted the previous part
![image](https://user-images.githubusercontent.com/75935737/156776863-f9245537-3535-4eed-a229-2e0f3b156520.png)
However, **errors** will still be reported like this
C:\Program Files\Android\android-backup-extractor-master\target> java -jar abe.jar unpack mihealth.bak mihealth.tar
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For"input string: "5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:232)
        at org.nick.abe.Main.main(Main.java:40)
"aused by: java.lang.NumberFormatException: For input string: "5
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)
        at java.base/java.lang.Integer.parseInt(Integer.java:786)
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:72)
        ... 1 more

**Comment by superbonaci** [comment]
Can you upload the backup of one entire file?
